#!/system/bin/sh
#
######################
# script made by rodionov
######################

echo 'noop' > /sys/block/mmcblk0/queue/scheduler
echo 'noop' > /sys/block/mmcblk1/queue/scheduler
chmod 644 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo '494000' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
chmod 444 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo '1' > /sys/devices/system/cpu/cpu1/online
chmod 644 /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo '494000' > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
chmod 444 /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo '0' > /sys/devices/system/cpu/cpu1/online
echo '1' > /sys/devices/system/cpu/cpu2/online
chmod 644 /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
echo '494000' > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
chmod 444 /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
echo '0' > /sys/devices/system/cpu/cpu2/online
echo '1' > /sys/devices/system/cpu/cpu3/online
chmod 644 /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
echo '494000' > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
chmod 444 /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
echo '0' > /sys/devices/system/cpu/cpu3/online
echo '20000 494000:50000 793000:50000 923000:50000 988000:50000' > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
echo '95' > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
echo '50000' > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
echo '1 494000:20 793000:50 923000:65 988000:80' > /sys/devices/system/cpu/cpufreq/interactive/target_loads
echo '80000' > /sys/devices/system/cpu/cpufreq/interactive/timer_rate
echo '30000' > /sys/devices/system/cpu/cpufreq/interactive/timer_slack
echo '256' > /sys/block/mmcblk0/queue/read_ahead_kb
echo '256' > /sys/block/mmcblk1/queue/read_ahead_kb
echo '640' > /proc/sys/kernel/random/read_wakeup_threshold
echo '1344' > /proc/sys/kernel/random/write_wakeup_threshold
swapoff /dev/block/zram0 > /dev/null 2>&1
echo '1' > /sys/block/zram0/reset
echo '0' > /sys/block/zram0/disksize
echo '545259520' > /sys/block/zram0/disksize
mkswap /dev/block/zram0 > /dev/null 2>&1
swapon /dev/block/zram0 > /dev/null 2>&1
echo '65' > /proc/sys/vm/swappiness
stop thermald



#
# done
#
######################
# script made by rodionov
######################

